# Generated by Django 4.0.4 on 2022-05-07 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SmsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=30)),
                ('date', models.BigIntegerField()),
                ('read', models.BooleanField(default=False)),
                ('content', models.CharField(max_length=300)),
                ('mobile', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'sms',
            },
        ),
    ]
