# Generated by Django 4.1.5 on 2023-01-10 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SmsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('sender', models.CharField(max_length=30, verbose_name='发件人号码')),
                ('person', models.CharField(max_length=30, verbose_name='发件人姓名')),
                ('date', models.BigIntegerField(verbose_name='发件日期')),
                ('read', models.BooleanField(default=False, verbose_name='是否已读')),
                ('content', models.CharField(max_length=1024, verbose_name='短信内容')),
                ('mobile', models.CharField(max_length=30, verbose_name='短信主人')),
            ],
            options={
                'db_table': 'sms',
            },
        ),
    ]
